# Generated by Django 3.2 on 2022-03-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tdee',
            field=models.IntegerField(blank=True, default=2000),
            preserve_default=False,
        ),
    ]
