# Generated by Django 3.2 on 2022-03-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_member_tdee'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tdee_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
