# Generated by Django 3.2 on 2022-03-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_alter_member_tdee_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tdee_update',
            field=models.DateTimeField(blank=True),
        ),
    ]
