# Generated by Django 3.2 on 2022-03-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_alter_member_tdee_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='activity',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='height',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='weight',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
