# Generated by Django 3.2 on 2022-03-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_auto_20220330_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
