# Generated by Django 3.2 on 2022-03-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_auto_20220330_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tdee_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
