# Generated by Django 3.2 on 2022-04-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_member_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tdee_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
