# Generated by Django 3.2 on 2022-04-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_alter_member_tdee_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='current_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
