# Generated by Django 3.2 on 2022-03-30 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeanTurkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coconut_oil', models.CharField(blank=True, max_length=254, null=True)),
                ('turkey_breast', models.CharField(blank=True, max_length=254, null=True)),
                ('onion', models.CharField(blank=True, max_length=254, null=True)),
                ('red_pepper', models.CharField(blank=True, max_length=254, null=True)),
                ('garlic_clove', models.CharField(blank=True, max_length=254, null=True)),
                ('tai_red', models.CharField(blank=True, max_length=254, null=True)),
                ('avocado', models.CharField(blank=True, max_length=254, null=True)),
                ('sour_cream', models.CharField(blank=True, max_length=254, null=True)),
                ('lime', models.CharField(blank=True, max_length=254, null=True)),
                ('green_veg', models.CharField(blank=True, max_length=254, null=True)),
                ('calories', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nutrition.calories')),
            ],
        ),
        migrations.CreateModel(
            name='LeanMince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coconut_oil', models.CharField(blank=True, max_length=254, null=True)),
                ('beef_mince', models.CharField(blank=True, max_length=254, null=True)),
                ('red_onion', models.CharField(blank=True, max_length=254, null=True)),
                ('mushrooms', models.CharField(blank=True, max_length=254, null=True)),
                ('mixed_herbs', models.CharField(blank=True, max_length=254, null=True)),
                ('smoked_paprika', models.CharField(blank=True, max_length=254, null=True)),
                ('tomato_puree', models.CharField(blank=True, max_length=254, null=True)),
                ('bbq_sauce', models.CharField(blank=True, max_length=254, null=True)),
                ('stock_cube', models.CharField(blank=True, max_length=254, null=True)),
                ('green_veg', models.CharField(blank=True, max_length=254, null=True)),
                ('avocado', models.CharField(blank=True, max_length=254, null=True)),
                ('calories', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nutrition.calories')),
            ],
        ),
        migrations.CreateModel(
            name='AromaticTurkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coconut_oil', models.CharField(blank=True, max_length=254, null=True)),
                ('turkey_breast', models.CharField(blank=True, max_length=254, null=True)),
                ('brown_rice', models.CharField(blank=True, max_length=254, null=True)),
                ('green_veg', models.CharField(blank=True, max_length=254, null=True)),
                ('sesame_seeds', models.CharField(blank=True, max_length=254, null=True)),
                ('soy_sauce', models.CharField(blank=True, max_length=254, null=True)),
                ('spring_onions', models.CharField(blank=True, max_length=254, null=True)),
                ('calories', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nutrition.calories')),
            ],
        ),
    ]
