# Generated by Django 3.2 on 2022-04-05 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCalories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_calories', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('dyn_ingredient_1', models.IntegerField(blank=True, null=True)),
                ('dyn_ingredient_2', models.IntegerField(blank=True, null=True)),
                ('dyn_ingredient_3', models.IntegerField(blank=True, null=True)),
                ('dyn_description_1', models.CharField(blank=True, max_length=254, null=True)),
                ('dyn_description_2', models.CharField(blank=True, max_length=254, null=True)),
                ('dyn_description_3', models.CharField(blank=True, max_length=254, null=True)),
                ('ingredient_1', models.CharField(blank=True, max_length=254, null=True)),
                ('ingredient_2', models.CharField(blank=True, max_length=254, null=True)),
                ('ingredient_3', models.CharField(blank=True, max_length=254, null=True)),
                ('ingredient_4', models.CharField(blank=True, max_length=254, null=True)),
                ('ingredient_5', models.CharField(blank=True, max_length=254, null=True)),
                ('ingredient_6', models.CharField(blank=True, max_length=254, null=True)),
                ('ingredient_7', models.CharField(blank=True, max_length=254, null=True)),
                ('ingredient_8', models.CharField(blank=True, max_length=254, null=True)),
                ('ingredient_9', models.CharField(blank=True, max_length=254, null=True)),
                ('ingredient_10', models.CharField(blank=True, max_length=254, null=True)),
                ('carb_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbs', to='nutrition.mealtype')),
                ('meal_calories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_cals', to='nutrition.mealcalories')),
            ],
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
