# Generated by Django 3.2 on 2022-04-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20220405_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealingredients',
            old_name='dyn_description_1',
            new_name='ingredient_11',
        ),
        migrations.RenameField(
            model_name='mealingredients',
            old_name='dyn_description_2',
            new_name='ingredient_12',
        ),
        migrations.RenameField(
            model_name='mealingredients',
            old_name='dyn_description_3',
            new_name='ingredient_13',
        ),
        migrations.RemoveField(
            model_name='mealingredients',
            name='dyn_ingredient_1',
        ),
        migrations.RemoveField(
            model_name='mealingredients',
            name='dyn_ingredient_2',
        ),
        migrations.RemoveField(
            model_name='mealingredients',
            name='dyn_ingredient_3',
        ),
    ]
