# Generated by Django 3.2 on 2022-03-30 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_aromaticturkey_leanmince_leanturkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aromaticturkey',
            name='calories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.calories'),
        ),
        migrations.AlterField(
            model_name='leanmince',
            name='calories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.calories'),
        ),
        migrations.AlterField(
            model_name='leanturkey',
            name='calories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.calories'),
        ),
    ]
