# Generated by Django 3.2 on 2022-05-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_auto_20220409_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealingredients',
            name='image_url',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
    ]
