# Generated by Django 3.2 on 2022-03-30 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_auto_20220330_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aromaticturkey',
            name='calories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calories_aromatic_turkey', to='nutrition.calories'),
        ),
        migrations.AlterField(
            model_name='leanmince',
            name='calories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calories_lean_mince', to='nutrition.calories'),
        ),
        migrations.AlterField(
            model_name='leanturkey',
            name='calories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calories_lean_turkey', to='nutrition.calories'),
        ),
    ]
