# Generated by Django 3.2 on 2022-05-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_mealingredients_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealingredients',
            name='image_url',
        ),
        migrations.AddField(
            model_name='mealingredients',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
