# Generated by Django 3.2 on 2022-03-31 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_auto_20220331_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('dyn_ingredient_1', models.CharField(blank=True, max_length=254, null=True)),
                ('dyn_ingredient_2', models.CharField(blank=True, max_length=254, null=True)),
                ('dyn_ingredient_3', models.CharField(blank=True, max_length=254, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.mealtype')),
            ],
        ),
    ]
