# Generated by Django 3.2 on 2022-05-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_auto_20220512_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealingredients',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
