# Generated by Django 3.2 on 2022-03-31 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_auto_20220331_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbs', to='nutrition.mealtype'),
        ),
    ]
