# Generated by Django 3.2 on 2022-03-31 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_alter_meal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='type',
            new_name='carb_type',
        ),
    ]
