# Generated by Django 3.2 on 2022-04-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_rename_type_meal_carb_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='ingredient_9',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
