# Generated by Django 3.2 on 2022-04-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_meal_ingredient_9'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='dyn_description_1',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='dyn_description_2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='dyn_description_3',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
