# Generated by Django 3.2 on 2022-04-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
